# Generated by Django 3.1.7 on 2021-04-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics_forum', '0002_auto_20210410_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('parent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
